[project]
name = 'Blockchain-Based-Specialized-Sports-Memorabilia-Authentication'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.authentication-certificate]
path = 'contracts/authentication-certificate.clar'
clarity_version = 2
epoch = 2.5

[contracts.item-registration]
path = 'contracts/item-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.player-verification]
path = 'contracts/player-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.provenance]
path = 'contracts/provenance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
